on: push

name: Render Video

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: video.mp4
          path: out/video.mp4
